/* ============================================================
   Le cartelle del vault, per la tendina «Cartella di archivio».

   Serve a non lasciare quel campo a testo libero: e' cosi' che sono
   nate le 114 diciture diverse ereditate da Access («CARTELLA - ...»,
   «DOX - ...»), che per giunta descrivono cartelle non piu' esistenti
   dopo il riordino del 2026.

   ⚠️ Questo campo dice dove il documento DEVE stare: e' l'intenzione,
   decisa al momento del protocollo. Dove il documento E' davvero lo
   dice Drive, ed e' un'altra cosa. Si tengono separate apposta, perche'
   quando divergono vuol dire che il documento non e' ancora stato
   smistato — o che e' finito altrove.

   Elenco rigenerato il 2026-08-28 dalla struttura reale, fino al terzo
   livello. Esclusi BK20260626, _PERSONALE, 5_MEDIA e gli scarti.
   Va rifatto quando la struttura del vault cambia.
   ============================================================ */

export const CARTELLE_VAULT = [
"1_PROGETTI",
"1_PROGETTI/2023_05_Revisione-sito-web-Tagliani",
"1_PROGETTI/2023_05_Revisione-sito-web-Tagliani/2026_07_23_materiali-inviati-Tagliani",
"1_PROGETTI/2023_05_Revisione-sito-web-Tagliani/2026_08_04_prototipo-XD-sito",
"1_PROGETTI/2023_05_Revisione-sito-web-Tagliani/2026_08_04_testi-sito-Tagliani",
"1_PROGETTI/2023_05_Revisione-sito-web-Tagliani/Materiali_sezione_Scuola",
"1_PROGETTI/2024 02 Palestra della sicurezza",
"1_PROGETTI/2024 10 08 Veneto Strade",
"1_PROGETTI/2025_03_Proposta_Cantiere_Scuola_Bormolini",
"1_PROGETTI/2026 02 04 Efficacia FORMAZIONE",
"1_PROGETTI/2026 03 03 Progetto BOLZANO",
"1_PROGETTI/2026_08_Controllo-AI-verbali",
"1_PROGETTI/2026_08_Proposta-evento-bambini-sicurezza",
"1_PROGETTI/2026_Dagli-errori-si-impara",
"1_PROGETTI/2026_Protocollo-intesa-Comune-di-Padova-cantieri-stradali",
"1_PROGETTI/Progetti_finanziati",
"1_PROGETTI/Progetti_finanziati/2012 NUOVO Progetto Pilota 2012",
"1_PROGETTI/Progetti_finanziati/2013 ICE",
"1_PROGETTI/Progetti_finanziati/2019 DGR540 Citta-intelligente (Centro Edile Palladio)",
"1_PROGETTI/Progetti_finanziati/2021 07 Progetto affiancamento tecnici cpt",
"1_PROGETTI/Progetti_finanziati/2023_03_Competenze-in-transizione",
"1_PROGETTI/Progetti_finanziati/2023_09_Simulatore_VR",
"1_PROGETTI/Progetti_finanziati/2026 INAIL ISI 2025 segnaletica stradale conselvana",
"1_PROGETTI/Progetti_finanziati/_da_smistare",
"1_PROGETTI/Progetti_finanziati/_da_verificare",
"2_AREE",
"2_AREE/Amministrazione",
"2_AREE/Amministrazione/CDA",
"2_AREE/Amministrazione/CV",
"2_AREE/Amministrazione/Documenti di identita",
"2_AREE/Amministrazione/Listini",
"2_AREE/Amministrazione/Planimetrie",
"2_AREE/Amministrazione/_da_OCR",
"2_AREE/Amministrazione/_da_classificare",
"2_AREE/Amministrazione/_da_verificare",
"2_AREE/Amministrazione/_storico segreteria CPT",
"2_AREE/Amministrazione/assicurazioni_tecnici",
"2_AREE/Amministrazione/contabilita_prima_nota",
"2_AREE/Amministrazione/contratti",
"2_AREE/Amministrazione/fatture",
"2_AREE/Amministrazione/inventario",
"2_AREE/Amministrazione/macchine_ufficio",
"2_AREE/Amministrazione/mandati_pagamenti",
"2_AREE/Amministrazione/materiale_stampa",
"2_AREE/Amministrazione/materiale_stampa_2026",
"2_AREE/Amministrazione/nomine",
"2_AREE/Amministrazione/ordini_cancelleria",
"2_AREE/Amministrazione/organigrammi",
"2_AREE/Amministrazione/personale",
"2_AREE/Amministrazione/planning",
"2_AREE/Amministrazione/privacy",
"2_AREE/Amministrazione/rendicontazioni",
"2_AREE/Amministrazione/riepiloghi_attivita_tecnici",
"2_AREE/Amministrazione/rimborsi",
"2_AREE/Amministrazione/sicurezza_sede",
"2_AREE/Amministrazione/statuto_e_accordi",
"2_AREE/Amministrazione/trasferte",
"2_AREE/Asseverazione",
"2_AREE/Asseverazione/Asseverazione_documenti_generali",
"2_AREE/Asseverazione/_DA_SMISTARE",
"2_AREE/Asseverazione/_export_gestionale",
"2_AREE/Asseverazione/_lavorazioni",
"2_AREE/Asseverazione/_modulistica",
"2_AREE/Asseverazione/_progetti_MOG",
"2_AREE/Asseverazione/_questionari imprese asseverate 2019",
"2_AREE/Asseverazione/_riferimento",
"2_AREE/Asseverazione/accordi_circolari",
"2_AREE/Asseverazione/asseveratori",
"2_AREE/Asseverazione/assicurazione",
"2_AREE/Asseverazione/attestazioni_rilasciate",
"2_AREE/Asseverazione/audit",
"2_AREE/Asseverazione/commissione",
"2_AREE/Asseverazione/imprese",
"2_AREE/Asseverazione/lettere_incarico",
"2_AREE/Asseverazione/offerte",
"2_AREE/Asseverazione/preventivi",
"2_AREE/Commissione_Sicurezza",
"2_AREE/Commissione_Sicurezza/_bozze_verbali",
"2_AREE/Commissione_Sicurezza/commissioni_riunite",
"2_AREE/Commissione_Sicurezza/componenti",
"2_AREE/Commissione_Sicurezza/convocazioni",
"2_AREE/Commissione_Sicurezza/materiale_riunioni",
"2_AREE/Commissione_Sicurezza/presenze",
"2_AREE/Commissione_Sicurezza/regolamento",
"2_AREE/Commissione_Sicurezza/verbali",
"2_AREE/Comunicazioni_Imprese",
"2_AREE/Comunicazioni_Imprese/2019-2021 avvisi da posta",
"2_AREE/Comunicazioni_Imprese/2020 10 pub google",
"2_AREE/Comunicazioni_Imprese/2021 03 MOSCONI comunicazione",
"2_AREE/Comunicazioni_Imprese/_da_smistare",
"2_AREE/Comunicazioni_Imprese/_da_verificare",
"2_AREE/Comunicazioni_Imprese/liste_contatti_campagne",
"2_AREE/Comunicazioni_Imprese/loghi_brand",
"2_AREE/Comunicazioni_Imprese/mailing_liste_storiche",
"2_AREE/Comunicazioni_Imprese/protocollo",
"2_AREE/Comunicazioni_Imprese/sito_web",
"2_AREE/Comunicazioni_Imprese/stampa_pubblicazioni",
"2_AREE/Enti",
"2_AREE/Enti/ANCE",
"2_AREE/Enti/ARPAV",
"2_AREE/Enti/CEIV",
"2_AREE/Enti/CPC Padova",
"2_AREE/Enti/Collegio Geometri Rovigo",
"2_AREE/Enti/Comitato Regionale di Coordinamento Veneto",
"2_AREE/Enti/Coordinamento Regionale CPT Veneto",
"2_AREE/Enti/FILCA CISL",
"2_AREE/Enti/FONDIMPRESA",
"2_AREE/Enti/FORMEDIL Italia",
"2_AREE/Enti/INAIL",
"2_AREE/Enti/INPS",
"2_AREE/Enti/SPISAL",
"2_AREE/Enti/Scuola_Edile",
"2_AREE/Eventi_Campagne",
"2_AREE/Eventi_Campagne/2009_05_29_Seminario-aggiornamento-CPT-Padova",
"2_AREE/Eventi_Campagne/2010_02_26_Seminario-aggiornamento-CPT-Padova",
"2_AREE/Eventi_Campagne/2010_04_09_Convegno-SPISAL-RSPP",
"2_AREE/Eventi_Campagne/2011_05_13_Seminario-differenze-di-genere",
"2_AREE/Eventi_Campagne/2013_10_18_Tavola-rotonda-delega-di-funzioni",
"2_AREE/Eventi_Campagne/2014_05_14_Convegno-AIF",
"2_AREE/Eventi_Campagne/2014_11_28_Convegno-SGSL",
"2_AREE/Eventi_Campagne/2015_07_03_Convegno-formazione",
"2_AREE/Eventi_Campagne/2015_10_30_Convegno-SIMLII",
"2_AREE/Eventi_Campagne/2016_11_25_Convegno-nuovo-codice-appalti",
"2_AREE/Eventi_Campagne/2017_02_24_Convegno-SGSL-e-MOGS",
"2_AREE/Eventi_Campagne/2017_03_Progetto-Sicuramente-in-crescita",
"2_AREE/Eventi_Campagne/2018_05_30_Convegno-RLS",
"2_AREE/Eventi_Campagne/2018_10_30_Convegno-Polizia",
"2_AREE/Eventi_Campagne/2019_02_15_Convegno-CAM",
"2_AREE/Eventi_Campagne/2019_07_05_Sicuramente",
"2_AREE/Eventi_Campagne/2019_11_Convegno-saldature",
"2_AREE/Eventi_Campagne/2020_02_Fiera-di-Padova-stand-Area-Sicurezza",
"2_AREE/Eventi_Campagne/2021_03_18_Convegno-Polizia-tachigrafo",
"2_AREE/Eventi_Campagne/2021_03_Opuscolo-servizi-CPT",
"2_AREE/Eventi_Campagne/2021_04_08_Seminario-tachigrafo-Polizia-Stradale",
"2_AREE/Eventi_Campagne/2021_11_18_Road-show",
"2_AREE/Eventi_Campagne/2022_01_Webinar-Fantini_DL-146-2021",
"2_AREE/Eventi_Campagne/2022_02_22_Webinar-scuole-edili-Veneto",
"2_AREE/Eventi_Campagne/2022_04_Campagna-comunicare-la-sicurezza",
"2_AREE/Eventi_Campagne/2022_Campagna-occhio-all-amianto_CNCPT",
"2_AREE/Eventi_Campagne/2023_04_14_Convegno-ANCE-Giovani-Ancona",
"2_AREE/Eventi_Campagne/2023_05_Campagna-opuscolo-calore",
"2_AREE/Eventi_Campagne/2023_10_Fiera-SAIE",
"2_AREE/Eventi_Campagne/2024_03_13_Convegno-L215",
"2_AREE/Eventi_Campagne/2024_05_22_Volantino-trovaci-sui-social",
"2_AREE/Eventi_Campagne/2024_12_Seminario-patente-a-crediti",
"2_AREE/Eventi_Campagne/2025_03_Proposta-gilet",
"2_AREE/Eventi_Campagne/2025_04_28_Giornata-mondiale-sicurezza",
"2_AREE/Eventi_Campagne/2025_10_23_Presentazione-La-Colonna-Massimiliana",
"2_AREE/Eventi_Campagne/2026_01_17_Evento-Formedil-Padova",
"2_AREE/Eventi_Campagne/2026_01_27_Convegno-report-annuale-CPT",
"2_AREE/Eventi_Campagne/2026_02_12_Spettacolo-20-grammi_road-show-ANCE",
"2_AREE/Eventi_Campagne/2026_03_03_Progetto-Near-Miss",
"2_AREE/Eventi_Campagne/2026_04_28_Giornata-mondiale-sicurezza",
"2_AREE/Eventi_Campagne/2026_04_30_Olimpiadi-della-sicurezza",
"2_AREE/Eventi_Campagne/2026_06_18_Convegno-Near-Miss",
"2_AREE/Eventi_Campagne/_invii massivi da posta 2013-2015",
"2_AREE/Eventi_Campagne/_materiale grafico da posta 2013-2021",
"2_AREE/Eventi_Campagne/_materiale_campagne",
"2_AREE/Eventi_Campagne/auguri_natalizi",
"2_AREE/Formazione",
"2_AREE/Formazione/Scuola_Edile_offerta_formativa",
"2_AREE/Formazione/_export_gestionale_corsi",
"2_AREE/Formazione/_riferimento",
"2_AREE/Formazione/anno_formativo",
"2_AREE/Formazione/attestati_emessi",
"2_AREE/Formazione/attrezzature",
"2_AREE/Formazione/collaborazione_art37-c12_imprese",
"2_AREE/Formazione/conferenze_cantiere",
"2_AREE/Formazione/corsi_a_catalogo",
"2_AREE/Formazione/docenze (fatture 2012-2015)",
"2_AREE/Formazione/edizioni_corsi",
"2_AREE/Formazione/formazione_tecnici_CPT",
"2_AREE/Formazione/iscrizioni",
"2_AREE/Formazione/lettere_incarico",
"2_AREE/Formazione/locandine",
"2_AREE/Formazione/materiale_didattico",
"2_AREE/Formazione/patentino_perforatore",
"2_AREE/Formazione/percorsi",
"2_AREE/Formazione/programmazione_corsi",
"2_AREE/Formazione/qualificazione_docenti",
"2_AREE/Formazione/registrazioni_online",
"2_AREE/Formazione/registri_presenze_online",
"2_AREE/Formazione/stage_valutazioni",
"2_AREE/Formazione/verifica_attestati_esterni",
"2_AREE/Servizi_CPT",
"2_AREE/Servizi_CPT/DPL NOTIFICHE PRELIMINARI",
"2_AREE/Servizi_CPT/RLS",
"2_AREE/Servizi_CPT/RLST",
"2_AREE/Servizi_CPT/Sorveglianza sanitaria",
"2_AREE/Servizi_CPT/VEM",
"2_AREE/Servizi_CPT/Veronese Impianti 2021",
"2_AREE/Servizi_CPT/_riferimento (materiale altri CPT)",
"2_AREE/Servizi_CPT/richieste",
"2_AREE/Sopralluoghi",
"2_AREE/Sopralluoghi/2026_08_08_figure-rev4",
"2_AREE/Sopralluoghi/_da_verificare",
"2_AREE/Sopralluoghi/_riferimento",
"2_AREE/Sopralluoghi/comunicazioni_imprese",
"2_AREE/Sopralluoghi/incarichi_visite",
"2_AREE/Sopralluoghi/mappatura",
"2_AREE/Sopralluoghi/procedura_operativa",
"2_AREE/Sopralluoghi/rapporto_sopralluogo_modulo_google",
"2_AREE/Sopralluoghi/schede_checklist",
"2_AREE/Sopralluoghi/statistiche",
"2_AREE/Sopralluoghi/verbali",
"2_AREE/Team_Tecnici",
"2_AREE/Team_Tecnici/20260304 Analisi tecnici",
"2_AREE/Team_Tecnici/AREE Tecnici",
"2_AREE/Team_Tecnici/Alberto_Lorenzin",
"2_AREE/Team_Tecnici/Anna_Migliolaro",
"2_AREE/Team_Tecnici/Balladore_Paolo",
"2_AREE/Team_Tecnici/Caon_Franco",
"2_AREE/Team_Tecnici/Donato_Chiffi",
"2_AREE/Team_Tecnici/Elisa_De_Gaspari",
"2_AREE/Team_Tecnici/Franco_Ruscitti",
"2_AREE/Team_Tecnici/Marco_Camuffo",
"2_AREE/Team_Tecnici/Michele_Ronchitelli",
"2_AREE/Team_Tecnici/Michele_Vianello",
"2_AREE/Team_Tecnici/Mirco_Canova",
"2_AREE/Team_Tecnici/Nicola_De_Marco",
"2_AREE/Team_Tecnici/Renato_Squizzato",
"2_AREE/Team_Tecnici/Sergio_Danesin",
"2_AREE/Team_Tecnici/Stefano_Bortolami",
"2_AREE/Team_Tecnici/Tommaso_Visentini",
"2_AREE/Team_Tecnici/Vania",
"2_AREE/Team_Tecnici/Visentini_Tommaso",
"2_AREE/Team_Tecnici/_da_OCR",
"2_AREE/Team_Tecnici/_da_verificare",
"2_AREE/Team_Tecnici/comunicazioni",
"2_AREE/Team_Tecnici/formazione tecnici CNCPT",
"2_AREE/Team_Tecnici/materiale_vestiario",
"2_AREE/Team_Tecnici/riunioni",
"2_AREE/Team_Tecnici/tecnic",
"3_RISORSE",
"3_RISORSE/Circolari_FORMEDIL_Italia",
"3_RISORSE/Circolari_FORMEDIL_Italia/2007",
"3_RISORSE/Circolari_FORMEDIL_Italia/2008",
"3_RISORSE/Circolari_FORMEDIL_Italia/2009",
"3_RISORSE/Circolari_FORMEDIL_Italia/2010",
"3_RISORSE/Circolari_FORMEDIL_Italia/2011",
"3_RISORSE/Circolari_FORMEDIL_Italia/2012",
"3_RISORSE/Circolari_FORMEDIL_Italia/2013",
"3_RISORSE/Circolari_FORMEDIL_Italia/2014",
"3_RISORSE/Circolari_FORMEDIL_Italia/2015",
"3_RISORSE/Circolari_FORMEDIL_Italia/2016",
"3_RISORSE/Circolari_FORMEDIL_Italia/2017",
"3_RISORSE/Circolari_FORMEDIL_Italia/2018",
"3_RISORSE/Circolari_FORMEDIL_Italia/2019",
"3_RISORSE/Circolari_FORMEDIL_Italia/2020",
"3_RISORSE/Circolari_FORMEDIL_Italia/2021",
"3_RISORSE/Circolari_FORMEDIL_Italia/2022",
"3_RISORSE/Circolari_FORMEDIL_Italia/2023",
"3_RISORSE/Circolari_FORMEDIL_Italia/2024",
"3_RISORSE/Circolari_FORMEDIL_Italia/2025",
"3_RISORSE/Circolari_FORMEDIL_Italia/2026",
"3_RISORSE/Circolari_FORMEDIL_Italia/senza-anno",
"3_RISORSE/Codici_ATECO",
"3_RISORSE/DPI",
"3_RISORSE/Guide_procedure",
"3_RISORSE/Guide_procedure/2008_CD_CPT-Treviso_Lavoro-Sicuro-in-Edilizia",
"3_RISORSE/Guide_procedure/2022_02_10_screenshot-webinar-L215-preposto",
"3_RISORSE/Guide_procedure/ANCE - Manuali applicativo SQuadra231",
"3_RISORSE/Guide_procedure/CAM ed ECOPROGETTISTA",
"3_RISORSE/Guide_procedure/CDS - Manuale CNCPT Digital Service",
"3_RISORSE/Guide_procedure/CEIV - Sportello Virtuale Casse Edili del Veneto",
"3_RISORSE/Guide_procedure/CEPAS qualificazione formazione",
"3_RISORSE/Guide_procedure/CPT Bergamo - pubblicazioni",
"3_RISORSE/Guide_procedure/CPT Padova - Pareri tecnici",
"3_RISORSE/Guide_procedure/CPT Padova - Pubblicazioni",
"3_RISORSE/Guide_procedure/CPT Torino - Guida alla sicurezza in edilizia",
"3_RISORSE/Guide_procedure/CPT Torino - Liste di controllo e manuali",
"3_RISORSE/Guide_procedure/CPT Torino - Manuale valutazione dei rischi",
"3_RISORSE/Guide_procedure/CRC Veneto - DVR standardizzato",
"3_RISORSE/Guide_procedure/EU-OSHA",
"3_RISORSE/Guide_procedure/EU-OSHA e articoli",
"3_RISORSE/Guide_procedure/Esempi MOG 231",
"3_RISORSE/Guide_procedure/FORMEDIL - Guide formazione",
"3_RISORSE/Guide_procedure/FORMEDIL - Patentino macchine complesse",
"3_RISORSE/Guide_procedure/FORMEDIL Italia - Manuali applicativi",
"3_RISORSE/Guide_procedure/GUIDE OPUSCOLI cantieri (raccolta da stampa_pubblicazioni)",
"3_RISORSE/Guide_procedure/Guide illustrate sicurezza in cantiere",
"3_RISORSE/Guide_procedure/INAIL - Documenti tecnici COVID-19 (2020)",
"3_RISORSE/Guide_procedure/INAIL Manuali e linee guida",
"3_RISORSE/Guide_procedure/ISPESL - linee guida",
"3_RISORSE/Guide_procedure/ISPRA Manuali e linee guida",
"3_RISORSE/Guide_procedure/MIT - Linee guida cantieri",
"3_RISORSE/Guide_procedure/MOG e SGSL - guide ufficiali",
"3_RISORSE/Guide_procedure/Materiali multilingue lavoratori stranieri",
"3_RISORSE/Guide_procedure/Misurazione oneri amministrativi SSL (MOA)",
"3_RISORSE/Guide_procedure/Modelli altri CPT e organismi paritetici",
"3_RISORSE/Guide_procedure/Notifiche preliminari - sistemi regionali",
"3_RISORSE/Guide_procedure/OHSAS 18001 e SGSL - raccolta di riferimento CPT",
"3_RISORSE/Guide_procedure/Privacy e GDPR",
"3_RISORSE/Guide_procedure/Procedure sicurezza officina e attrezzature",
"3_RISORSE/Guide_procedure/Procedure visite - altri CPT ed enti",
"3_RISORSE/Guide_procedure/Protocolli intesa nazionali CNCPT",
"3_RISORSE/Guide_procedure/Silice e amianto",
"3_RISORSE/Guide_procedure/Sistemi anticaduta - raccolta Mistral",
"3_RISORSE/Guide_procedure/Sorveglianza sanitaria - riferimenti di altri enti",
"3_RISORSE/Guide_procedure/Veneto Lavoro - Monitoraggio GOL",
"3_RISORSE/Guide_procedure/Whistleblowing",
"3_RISORSE/Guide_procedure/_biblioteca sito web CPT",
"3_RISORSE/Guide_procedure/pubblicazioni CPT Padova da posta",
"3_RISORSE/Modelli",
"3_RISORSE/Modulistica",
"3_RISORSE/Modulistica/Addestramento",
"3_RISORSE/Modulistica/RLS",
"3_RISORSE/Modulistica/_da sito web CPT",
"3_RISORSE/Modulistica/_fac-simile_attestati",
"3_RISORSE/Modulistica/_prove_e_bozze",
"3_RISORSE/Modulistica/etichette e copertine (storico CPT)",
"3_RISORSE/Normativa",
"3_RISORSE/Normativa/Accordo Stato-Regioni 2025 formazione",
"3_RISORSE/Normativa/Appalti",
"3_RISORSE/Normativa/CCNL Edilizia",
"3_RISORSE/Normativa/COVID19",
"3_RISORSE/Normativa/DLgs 81-2008 - testo e allegati (raccolta CPT 2008)",
"3_RISORSE/Normativa/Formatori",
"3_RISORSE/Normativa/Patente a crediti",
"3_RISORSE/Normativa/Ponteggi e opere provvisionali",
"3_RISORSE/Normativa/Testo unico 81-2008",
"3_RISORSE/Normativa/UNI e norme tecniche",
"3_RISORSE/Normativa/_da sito web CPT",
"3_RISORSE/Notiziari",
"3_RISORSE/Notiziari/NOTIZIARI",
"3_RISORSE/Tabelle_riferimento",
"4_ARCHIVIO",
"4_ARCHIVIO/2026-08-11 Residui 0000 DESK",
"4_ARCHIVIO/Archivi di posta (PST-OST)",
"4_ARCHIVIO/COVID-19 - materiale di riferimento di altri enti (2020)",
"4_ARCHIVIO/COVID-19 - materiale di riferimento di altri enti (2020)/ANCE Verona - riapertura cantieri",
"4_ARCHIVIO/COVID-19 - materiale di riferimento di altri enti (2020)/CNCPT e CEFS",
"4_ARCHIVIO/COVID-19 - materiale di riferimento di altri enti (2020)/CPT Varese",
"4_ARCHIVIO/COVID-19 - materiale di riferimento di altri enti (2020)/Cartellonistica CPT Padova (2020)",
"4_ARCHIVIO/COVID-19 - materiale di riferimento di altri enti (2020)/Cartellonistica e locandine",
"4_ARCHIVIO/COVID-19 - materiale di riferimento di altri enti (2020)/Documenti locali e istituzionali",
"4_ARCHIVIO/COVID-19 - materiale di riferimento di altri enti (2020)/ESEM-CPT Milano",
"4_ARCHIVIO/COVID-19 - materiale di riferimento di altri enti (2020)/Modulistica e procedure per le imprese",
"4_ARCHIVIO/COVID-19 - materiale di riferimento di altri enti (2020)/Regione FVG",
"4_ARCHIVIO/CPIPE (eredita pre-fusione)",
"4_ARCHIVIO/CPIPE (eredita pre-fusione)/Donatella",
"4_ARCHIVIO/CPTPDScheda2009",
"4_ARCHIVIO/Cassa Edile - documenti di segreteria 2004-2009",
"4_ARCHIVIO/Cassa Edile - documenti di segreteria 2004-2009/DISTINTE RACCOMANDATE",
"4_ARCHIVIO/Cassa Edile - documenti di segreteria 2004-2009/ETICHETTE",
"4_ARCHIVIO/Cassa Edile - documenti di segreteria 2004-2009/FAX CASSA EDILE",
"4_ARCHIVIO/Cassa Edile - documenti di segreteria 2004-2009/RACCOMANDATE",
"4_ARCHIVIO/Cassa Edile - documenti di segreteria 2004-2009/VESTIARIO",
"4_ARCHIVIO/Cassa Edile - documenti di segreteria 2004-2009/modelli",
"4_ARCHIVIO/Cassa Edile - documenti di segreteria 2004-2009/rubrica",
"4_ARCHIVIO/Claude_Archivio",
"4_ARCHIVIO/Claude_Archivio/2026-07-31 archiviazioni approvate",
"4_ARCHIVIO/Claude_Archivio/memory DIRIVE Obsidian",
"4_ARCHIVIO/Comitato Edile COVID-19",
"4_ARCHIVIO/Comitato Edile COVID-19/ASC",
"4_ARCHIVIO/Comitato Edile COVID-19/Cartelli e loghi",
"4_ARCHIVIO/Comitato Edile COVID-19/Comitato COVID",
"4_ARCHIVIO/Comitato Edile COVID-19/Comunicazioni imprese",
"4_ARCHIVIO/Comitato Edile COVID-19/Consulenza TIEMME",
"4_ARCHIVIO/Comitato Edile COVID-19/Moduli e checklist",
"4_ARCHIVIO/Comitato Edile COVID-19/Protocolli e normativa",
"4_ARCHIVIO/Comitato Edile COVID-19/Richieste e attestazioni",
"4_ARCHIVIO/Comitato Edile COVID-19/Verbali riunioni",
"4_ARCHIVIO/Comitato Edile COVID-19/_bozze e lavorazioni",
"4_ARCHIVIO/Comitato Edile COVID-19/da posta 2020-2021",
"4_ARCHIVIO/Corrispondenza CPT 2007-2026",
"4_ARCHIVIO/Corrispondenza CPT 2007-2026/2006",
"4_ARCHIVIO/Corrispondenza CPT 2007-2026/2007",
"4_ARCHIVIO/Corrispondenza CPT 2007-2026/2007-2009 posta elettronica",
"4_ARCHIVIO/Corrispondenza CPT 2007-2026/2008",
"4_ARCHIVIO/Corrispondenza CPT 2007-2026/2009",
"4_ARCHIVIO/Corrispondenza CPT 2007-2026/2010",
"4_ARCHIVIO/Corrispondenza CPT 2007-2026/2011",
"4_ARCHIVIO/Corrispondenza CPT 2007-2026/2012",
"4_ARCHIVIO/Corrispondenza CPT 2007-2026/2013",
"4_ARCHIVIO/Corrispondenza CPT 2007-2026/2014",
"4_ARCHIVIO/Corrispondenza CPT 2007-2026/2015",
"4_ARCHIVIO/Corrispondenza CPT 2007-2026/2016",
"4_ARCHIVIO/Corrispondenza CPT 2007-2026/2017",
"4_ARCHIVIO/Corrispondenza CPT 2007-2026/2018",
"4_ARCHIVIO/Corrispondenza CPT 2007-2026/2019",
"4_ARCHIVIO/Corrispondenza CPT 2007-2026/2020",
"4_ARCHIVIO/Corrispondenza CPT 2007-2026/2021",
"4_ARCHIVIO/Corrispondenza CPT 2007-2026/2022",
"4_ARCHIVIO/Corrispondenza CPT 2007-2026/2023",
"4_ARCHIVIO/Corrispondenza CPT 2007-2026/2024",
"4_ARCHIVIO/Corrispondenza CPT 2007-2026/2025",
"4_ARCHIVIO/Corrispondenza CPT 2007-2026/2026",
"4_ARCHIVIO/Corrispondenza CPT 2007-2026/_PEC recuperate dalla posta 2013-2021",
"4_ARCHIVIO/Corrispondenza CPT 2007-2026/_lotto da posta 2026-08",
"4_ARCHIVIO/Corrispondenza CPT 2007-2026/_posta completa (eml)",
"4_ARCHIVIO/Corrispondenza CPT 2007-2026/senza-anno",
"4_ARCHIVIO/CptPdAnalisi2009",
"4_ARCHIVIO/CptPdAnalisi2009/20200225CptPdAnalisi2009BACKUP",
"4_ARCHIVIO/CptPdAnalisi2009/20240515 Statistiche per Presidente",
"4_ARCHIVIO/CptPdAnalisi2009/DBCxRestore",
"4_ARCHIVIO/CptPdAnalisi2009/Dati",
"4_ARCHIVIO/CptPdAnalisi2009/Dati analisi vecchie",
"4_ARCHIVIO/CptPdAnalisi2009/OLD",
"4_ARCHIVIO/CptPdAnalisi2009/Silvana Giugno",
"4_ARCHIVIO/CptPdAnalisi2009/silvana maggio",
"4_ARCHIVIO/Eventi_terminati",
"4_ARCHIVIO/Normativa abrogata - raccolta storica CPT",
"4_ARCHIVIO/Posta segreteria CPT 2011-2012 (backup di casella)",
"4_ARCHIVIO/Posta segreteria CPT 2011-2012 (backup di casella)/_sorgente (eml e zip originali)",
"4_ARCHIVIO/Posta segreteria CPT 2011-2012 (backup di casella)/_spam_e_catene",
"4_ARCHIVIO/Posta segreteria CPT 2011-2012 (backup di casella)/allegati_nuovi",
"4_ARCHIVIO/Progetti_terminati",
"4_ARCHIVIO/Progetti_terminati/2010_04_Corso_RSPP_Modulo_A",
"4_ARCHIVIO/Progetti_terminati/2010_05_Corso_Datori_di_Lavoro_e_Dirigenti",
"4_ARCHIVIO/Progetti_terminati/2010_11_Corso_Preposti_Capicantiere_Capisquadra",
"4_ARCHIVIO/Progetti_terminati/2010_11_Corso_Sicurezza_Lavoratori_Cassa_Edile",
"4_ARCHIVIO/Progetti_terminati/2011_03_Corso_Preposti_Capicantiere_Capisquadra_Padova",
"4_ARCHIVIO/Progetti_terminati/2011_11_Corso_Preposti_Capicantiere_Capisquadra_Padova",
"4_ARCHIVIO/Progetti_terminati/2011_2014_Progetto_INAIL_Bollino_Blu",
"4_ARCHIVIO/Progetti_terminati/2011_Modulistica_Formazione_Aziende_Dipendenti",
"4_ARCHIVIO/Progetti_terminati/2012_01_Seminario_Nuovi_Schemi_Operativi_Sicurezza",
"4_ARCHIVIO/Progetti_terminati/2012_06_Seminario_Linee_Vita",
"4_ARCHIVIO/Progetti_terminati/2012_11_Incontro_obblighi_formativi_sicurezza_edile",
"4_ARCHIVIO/Progetti_terminati/2012_Olidalmine_demo_gestionale_visite",
"4_ARCHIVIO/Progetti_terminati/2012_Perforatori_Patentino_Macchine_Complesse",
"4_ARCHIVIO/Progetti_terminati/2013_05_Incontro_Cantieri_Stradali_Traffico_Veicolare",
"4_ARCHIVIO/Progetti_terminati/2013_06_Corso_Primo_Soccorso",
"4_ARCHIVIO/Progetti_terminati/2013_10_Convegno_Delega_di_Funzioni",
"4_ARCHIVIO/Progetti_terminati/2013_2016_Progetto_INAIL_SistemFare",
"4_ARCHIVIO/Progetti_terminati/2014_07_Convegno_Verifiche_Periodiche_Attrezzature",
"4_ARCHIVIO/Progetti_terminati/2014_Bando_INAIL_FIPIT_attestazioni_CPT_a_imprese",
"4_ARCHIVIO/Progetti_terminati/2015_Avviso_INAIL_progetti_prevenzionali_valutazione",
"4_ARCHIVIO/Progetti_terminati/2016_2020_Progetto_INAIL_Balladore",
"4_ARCHIVIO/Progetti_terminati/2017_Bando_INAIL_FIPIT_Callegaro_Gemino",
"4_ARCHIVIO/Progetti_terminati/2018_06_Progetto_Formativo_IeFP_Operatore_Edile_Cod182-1-752-2018",
"4_ARCHIVIO/Progetti_terminati/2018_12_Progetto_ARLES",
"4_ARCHIVIO/Progetti_terminati/2019_03_Lavoro_e_legalita",
"4_ARCHIVIO/Progetti_terminati/2019_05_Progetto_540_VI-PD_Droni",
"4_ARCHIVIO/Progetti_terminati/2019_05_Progetto_540_VI-PD_base",
"4_ARCHIVIO/Progetti_terminati/2019_11_IFTS_Tecnico_Organizzazione_Cantiere",
"4_ARCHIVIO/Progetti_terminati/2019_2020_Servizio_DPI_anticaduta_mai_avviato",
"4_ARCHIVIO/Progetti_terminati/2019_2022_Progetto_CQ_DGR394",
"4_ARCHIVIO/Progetti_terminati/2020_10_Proposta_pianificazione_processo",
"4_ARCHIVIO/Progetti_terminati/2020_10_Webinar_Comunicazione",
"4_ARCHIVIO/Progetti_terminati/2020_12_Slide_Corso_Preposti",
"4_ARCHIVIO/Progetti_terminati/2020_2021_Progetto_ALISEI_CNCPT_UniMi",
"4_ARCHIVIO/Progetti_terminati/2020_2021_Progetto_FORMEDIL_CNCPT_Ecobonus_110_Percorso1",
"4_ARCHIVIO/Progetti_terminati/2020_Collaborazione_UNIVR_Analisi_Dati_Cantieri",
"4_ARCHIVIO/Progetti_terminati/2020_Formazione_COVID",
"4_ARCHIVIO/Progetti_terminati/2020_Presentazione_ReMoVe_Veneto_Strade",
"4_ARCHIVIO/Progetti_terminati/2020_Progetto_MAIDA_Progettare_Ecosostenibile_CAM",
"4_ARCHIVIO/Progetti_terminati/2021_05_Corso_Antincendio_Mura_di_Padova",
"4_ARCHIVIO/Progetti_terminati/2021_12_Droni_Rilievo_3D",
"4_ARCHIVIO/Progetti_terminati/2021_12_Materiali_Innovativi_Edilizia_Futuro",
"4_ARCHIVIO/Progetti_terminati/2021_2022_Progetti_SPISAL_CPC",
"4_ARCHIVIO/Progetti_terminati/2021_2022_Progetto_Erasmus_Ecobuild",
"4_ARCHIVIO/Progetti_terminati/2021_2024_Progetto_INAIL_Informare_in_Sicurezza_mai_attuato",
"4_ARCHIVIO/Progetti_terminati/2021_Bando_ISI_INAIL_2020_atti_imprese",
"4_ARCHIVIO/Progetti_terminati/2021_Campagna_Corsi_RSPP",
"4_ARCHIVIO/Progetti_terminati/2021_Corso_Auditor_Sistemi_Gestione_SSL",
"4_ARCHIVIO/Progetti_terminati/2021_Fondimpresa_Mai_Avviato",
"4_ARCHIVIO/Progetti_terminati/2021_Percorso_Formativo_Restauratori",
"4_ARCHIVIO/Progetti_terminati/2021_Work_Experience_MMT",
"4_ARCHIVIO/Progetti_terminati/2022_01_IFTS_stub",
"4_ARCHIVIO/Progetti_terminati/2022_02_Webinar_RSPP_Risponde_Aggiornamento_DLgs81",
"4_ARCHIVIO/Progetti_terminati/2022_02_Webinar_Ruolo_del_Preposto_TV_PD",
"4_ARCHIVIO/Progetti_terminati/2022_06_Webinar_Antincendio_Formedil",
"4_ARCHIVIO/Progetti_terminati/2022_2025_Progetto_INAIL_STRESS_Scuole_Edili_Veneto",
"4_ARCHIVIO/Progetti_terminati/2022_Progetto_Sicuri_si_Diventa_Tutor_Aziendale",
"4_ARCHIVIO/Progetti_terminati/2023_06_Webinar_Diisocianati",
"4_ARCHIVIO/Progetti_terminati/2023_2024_Tirocini_GOL_Due_Palazzi",
"4_ARCHIVIO/Progetti_terminati/2023_2025_Progetto_Soft_Skill_Sicurezza",
"4_ARCHIVIO/Progetti_terminati/2024_06_Seminario_AI_Sicurezza_Cantiere",
"4_ARCHIVIO/Progetti_terminati/2024_2025_Corsi_Restauro_DGR654",
"4_ARCHIVIO/Progetti_terminati/2024_Corso_comunicazione_dipendenti_Formedil",
"4_ARCHIVIO/Progetti_terminati/2024_GOL_Percorso2_Upskilling_patentini_macchine",
"4_ARCHIVIO/Progetti_terminati/2024_Progetto_CPC_Costruiamo_Inclusione_in_Sicurezza_migranti_mai_presentato",
"4_ARCHIVIO/Progetti_terminati/2024_Work_Experience_Esperienza_su_misura_valutazione_bando",
"4_ARCHIVIO/Progetti_terminati/2025_01_Convegno_Patente_a_Crediti",
"4_ARCHIVIO/Scuola Edile - materiale sciolto 2014-2017 (eredita)",
"4_ARCHIVIO/Scuola Edile - posta casella condivisa 2019-2021",
"4_ARCHIVIO/Scuola Edile - posta casella condivisa 2019-2021/2019",
"4_ARCHIVIO/Scuola Edile - posta casella condivisa 2019-2021/2020",
"4_ARCHIVIO/Scuola Edile - posta casella condivisa 2019-2021/2021",
"4_ARCHIVIO/Servizio consulenza COVID-19 alle imprese (2020)",
"4_ARCHIVIO/Vecchie visite CPT - archivi cifrati",
"4_ARCHIVIO/Vecchie visite CPT - archivi cifrati/IMPRESE E CANTIERI PROBLEMATICI",
"4_ARCHIVIO/Vecchie visite CPT - archivi cifrati/Statistiche",
"4_ARCHIVIO/Vecchie visite CPT - archivi cifrati/Trasmissioni mensili tecnici 2013-2014 (da posta)",
"4_ARCHIVIO/Vecchie visite CPT - archivi cifrati/VERIFICHE 2007",
"4_ARCHIVIO/Vecchie visite CPT - archivi cifrati/VERIFICHE 2008",
"4_ARCHIVIO/Vecchie visite CPT - archivi cifrati/VERIFICHE 2009",
"4_ARCHIVIO/Vecchie visite CPT - archivi cifrati/VERIFICHE 2010",
"4_ARCHIVIO/Vecchie visite CPT - archivi cifrati/VERIFICHE 2011",
"4_ARCHIVIO/Verifiche di cantiere 2007-2011 (da vecchio PC)",
"4_ARCHIVIO/Verifiche di cantiere 2007-2011 (da vecchio PC)/CPTPDScheda2009",
"4_ARCHIVIO/Verifiche di cantiere 2007-2011 (da vecchio PC)/Statistiche",
"4_ARCHIVIO/Verifiche di cantiere 2007-2011 (da vecchio PC)/VERIFICHE 2008",
"4_ARCHIVIO/Verifiche di cantiere 2007-2011 (da vecchio PC)/VERIFICHE 2009",
"4_ARCHIVIO/Verifiche di cantiere 2007-2011 (da vecchio PC)/VERIFICHE 2010",
"4_ARCHIVIO/Verifiche di cantiere 2007-2011 (da vecchio PC)/VERIFICHE 2011",
"4_ARCHIVIO/Verifiche di cantiere 2007-2011 (da vecchio PC)/Visite in cantiere lug sett 09",
"9_APPLICATIVI",
"9_APPLICATIVI/CD Rumore e Vibrazioni - CPT Torino 2012",
"9_APPLICATIVI/CD Rumore e Vibrazioni - CPT Torino 2012/1 - Manuale",
"9_APPLICATIVI/CD Rumore e Vibrazioni - CPT Torino 2012/2 - Banca Dati",
"9_APPLICATIVI/CD Rumore e Vibrazioni - CPT Torino 2012/3 - Misure fonometriche e accelerometriche",
"9_APPLICATIVI/CD Rumore e Vibrazioni - CPT Torino 2012/4 - Fogli di calcolo",
"9_APPLICATIVI/CDS - CNCPT Digital Services",
"9_APPLICATIVI/CPP12 - Conoscere per Prevenire (CD-ROM CPT Torino)",
"9_APPLICATIVI/CPP12 - Conoscere per Prevenire (CD-ROM CPT Torino)/Aar",
"9_APPLICATIVI/CPP12 - Conoscere per Prevenire (CD-ROM CPT Torino)/Bin",
"9_APPLICATIVI/CPP12 - Conoscere per Prevenire (CD-ROM CPT Torino)/Cpt",
"9_APPLICATIVI/CPP12 - Conoscere per Prevenire (CD-ROM CPT Torino)/Doc",
"9_APPLICATIVI/CPP12 - Conoscere per Prevenire (CD-ROM CPT Torino)/Prg",
"9_APPLICATIVI/Claude",
"9_APPLICATIVI/Claude/Artifacts",
"9_APPLICATIVI/Claude/BD Access",
"9_APPLICATIVI/Claude/F_CASA",
"9_APPLICATIVI/Claude/Memory Copywriter",
"9_APPLICATIVI/Claude/PWA CANTIERI GOOGLE",
"9_APPLICATIVI/Claude/Scheduled",
"9_APPLICATIVI/Claude/Simulatore",
"9_APPLICATIVI/Claude/memory Bacheca RSU",
"9_APPLICATIVI/Claude/memory Estetica",
"9_APPLICATIVI/Claude/memory Gestionale visite",
"9_APPLICATIVI/Claude/memory SERVIZI",
"9_APPLICATIVI/Claude/memory SOCIAL",
"9_APPLICATIVI/DB CPT storici (vecchio PC)",
"9_APPLICATIVI/Formedil_Servizi_PWA",
"9_APPLICATIVI/Formedil_Servizi_PWA/_test_data",
"9_APPLICATIVI/GSuite_provisioning",
"9_APPLICATIVI/Gestionale_Visite",
"9_APPLICATIVI/Gestionale_Visite/01 Sopralluoghi in cantiere",
"9_APPLICATIVI/Gestionale_Visite/02 Dati e anagrafiche",
"9_APPLICATIVI/Gestionale_Visite/10_Allegatti_doc_ASS",
"9_APPLICATIVI/Gestionale_Visite/11_Documenti_protocollo",
"9_APPLICATIVI/Gestionale_Visite/Foto Segnalazioni CPT",
"9_APPLICATIVI/Gestionale_Visite_APP",
"9_APPLICATIVI/Gestionale_Visite_APP/AsseverazioneAPP",
"9_APPLICATIVI/Gestionale_Visite_APP/Documentazione",
"9_APPLICATIVI/Gestionale_Visite_APP/gestionale",
"9_APPLICATIVI/Gestionale_Visite_APP/gestionale-visite",
"9_APPLICATIVI/Gestionale_Visite_APP/import_access_2026-07-15",
"9_APPLICATIVI/Gestionale_Visite_APP/import_access_imprese_2026-08-13",
"9_APPLICATIVI/Gestionale_Visite_APP/import_access_protocollo_2026-08-13",
"9_APPLICATIVI/Gestionale_Visite_APP/import_ceiv",
"9_APPLICATIVI/Gestionale_Visite_APP/import_checklist_2026-08-07",
"9_APPLICATIVI/Gestionale_Visite_APP/import_visite_2023_2024",
"9_APPLICATIVI/Gestionale_Visite_APP/import_visite_2024_2025",
"9_APPLICATIVI/Gestionale_Visite_APP/import_visite_2026-07-29",
"9_APPLICATIVI/Gestionale_Visite_APP/import_visite_2026-08-04",
"9_APPLICATIVI/Gestionale_Visite_APP/import_visite_2026-08-10",
"9_APPLICATIVI/Gestionale_Visite_APP/import_visite_2026-08-25",
"9_APPLICATIVI/Gestionale_Visite_APP/import_visite_excel_2026-07-16",
"9_APPLICATIVI/Gestionale_Visite_APP/import_visite_modulo_2026-07-24",
"9_APPLICATIVI/Gestionale_Visite_APP/manutenzione",
"9_APPLICATIVI/Gestionale_Visite_APP/ocr_asseverazione_2026-08-07",
"9_APPLICATIVI/Gestionale_Visite_APP/screenshots",
"9_APPLICATIVI/Gestionale_Visite_APP/segreteria-app",
"9_APPLICATIVI/Gestionale_Visite_APP/snap_visite",
"9_APPLICATIVI/Gestionale_Visite_APP/sql_controlli_2026-08-03",
"9_APPLICATIVI/Gestionale_Visite_APP/test_output_2026",
"9_APPLICATIVI/Gsuite",
"9_APPLICATIVI/Gsuite/2021 Rovigo",
"9_APPLICATIVI/Gsuite/Account - Alunni Docenti account scuola",
"9_APPLICATIVI/Gsuite/Accreditamento",
"9_APPLICATIVI/Gsuite/Calendario corsi presenza",
"9_APPLICATIVI/Gsuite/Corsi Andrea FAD",
"9_APPLICATIVI/Gsuite/Guide Gsuite",
"9_APPLICATIVI/Gsuite/LOG",
"9_APPLICATIVI/Gsuite/Lezioni formazione GSUITE",
"9_APPLICATIVI/Gsuite/Modelli per inserimento nuovi account",
"9_APPLICATIVI/Gsuite/Orientamento apprendistato Giada",
"9_APPLICATIVI/Gsuite/Street view",
"9_APPLICATIVI/Gsuite/Verifica sito e doc scuola",
"9_APPLICATIVI/OLIDALMINE DB",
"9_APPLICATIVI/OLIDALMINE SOFTWARE VISITE IN CANTIERE",
"9_APPLICATIVI/OSSERVATORIO VISITE 2026",
"9_APPLICATIVI/OSSERVATORIO VISITE 2026/files",
"9_APPLICATIVI/Programmi",
"9_APPLICATIVI/Protocollo CPT (storico)",
"9_APPLICATIVI/RLST modulo online",
"9_APPLICATIVI/SERVIZI",
"9_APPLICATIVI/SERVIZI/APP Conferenze di Cantiere",
"9_APPLICATIVI/SERVIZI/AVVIO CORSI",
"9_APPLICATIVI/SERVIZI/Comitato Edile COVID-19",
"9_APPLICATIVI/SERVIZI/Modulo richiesta Conferenza di Cantiere",
"9_APPLICATIVI/SERVIZI/Non usato",
"9_APPLICATIVI/SERVIZI/Opuscolo",
"9_APPLICATIVI/SERVIZI/PDF_ricevuti",
"9_APPLICATIVI/SERVIZI/PWA",
"9_APPLICATIVI/SERVIZI/Portale Formedil – Allegati",
"9_APPLICATIVI/SERVIZI/Teplate servizi",
"9_APPLICATIVI/SERVIZI/documenti",
"9_APPLICATIVI/SERVIZI/foto",
"9_APPLICATIVI/Sito web CPT",
"9_APPLICATIVI/Sito web CPT/_generale",
"9_APPLICATIVI/Sito web CPT/codice",
"9_APPLICATIVI/Sito web CPT/costruzione-sito",
"9_APPLICATIVI/Sito web CPT/notizie-pubblicate",
"9_APPLICATIVI/Software visite CPT (storico)",
"9_APPLICATIVI/Software visite CPT (storico)/BACKUP (CptPdAnalisi2008 e archivi rar)",
"9_APPLICATIVI/Software visite CPT (storico)/CptPdAnalisi2009",
"9_APPLICATIVI/Software visite CPT (storico)/Programma CNCPT",
"9_APPLICATIVI/Valutazione_Piattaforme_Elearning",
"9_APPLICATIVI/qrcodelib"
];
