-- ============================================================
-- ABBINAMENTI ALLIEVI-AZIENDE DELLA SCUOLA → INCARICHI DI VISITA STAGE
-- 10/09/2026, chiesto dall'utente.
--
-- Due volte l'anno la didattica della Scuola (Barbara Bertan per Padova,
-- Alessia Ranci per Stanghella) manda il Word con gli abbinamenti: per ogni
-- allievo l'impresa, i cantieri, il tutor, l'orario. Ogni riga e' una
-- richiesta di visita allo stagista. L'app segreteria legge il Word, fa
-- controllare le righe e le conferma: ogni riga diventa un incarico nel
-- gestionale visite per il tecnico scelto.
--
-- Decisioni dell'utente (10/09/2026, scritte anche nel CLAUDE.md):
--   * NESSUNA autorizzazione del Direttore: e' un costo figurativo della
--     Scuola, in eccezione alla regola dei servizi CPT;
--   * solo file Word (.docx);
--   * tecnico proposto per zona; se il file ha la colonna TECNICO vale quella.
--
-- Il numero dell'incarico prosegue il contatore interno (serie richieste
-- 95/2014 → oltre 1083): e' un numero di pratica, non un protocollo.
-- Qui lo assegna il database, in una transazione con la tabella bloccata,
-- invece del max+1 calcolato nel browser: con dieci righe per volta due
-- inserimenti vicini si pesterebbero i piedi.
-- ============================================================

create table if not exists public.s_stage_elenchi (
  id                bigint generated by default as identity primary key,
  anno_scolastico   text not null check (anno_scolastico ~ '^[0-9]{4}-[0-9]{4}$'),
  classe            smallint not null check (classe between 1 and 5),
  sede              text not null check (sede in ('Padova', 'Stanghella')),
  dal               date,
  al                date,
  ore_giorno        numeric,
  ore_totali        numeric,
  richiedente_nome  text,
  richiedente_email text,
  data_richiesta    date not null default current_date,   -- quando e' arrivato l'elenco
  intestazione      text,                                 -- il testo sopra la tabella, com'era
  file_nome         text,
  file_drive_id     text,
  file_drive_url    text,
  note              text,
  creato_il         timestamptz not null default now(),
  creato_da         text,
  aggiornato_il     timestamptz not null default now(),
  aggiornato_da     text,
  -- un elenco per classe, sede e anno: una versione aggiornata aggiunge
  -- gli allievi nuovi allo stesso elenco invece di crearne un secondo
  constraint s_stage_elenchi_uno_per_classe unique (anno_scolastico, classe, sede)
);

comment on table public.s_stage_elenchi is
  'Abbinamenti allievi-aziende mandati dalla Scuola (Word). Ogni allievo diventa un incarico di visita stage (incarichi.stage_elenco_id). Nessuna autorizzazione del Direttore: costo figurativo della Scuola (regola del 10/09/2026).';

alter table public.s_stage_elenchi enable row level security;

drop policy if exists s_stage_elenchi_sel on public.s_stage_elenchi;
drop policy if exists s_stage_elenchi_ins on public.s_stage_elenchi;
drop policy if exists s_stage_elenchi_upd on public.s_stage_elenchi;
drop policy if exists s_stage_elenchi_del on public.s_stage_elenchi;
create policy s_stage_elenchi_sel on public.s_stage_elenchi for select to authenticated
  using (public.is_gestione_incarichi());
create policy s_stage_elenchi_ins on public.s_stage_elenchi for insert to authenticated
  with check (public.is_gestione_incarichi());
create policy s_stage_elenchi_upd on public.s_stage_elenchi for update to authenticated
  using (public.is_gestione_incarichi()) with check (public.is_gestione_incarichi());
create policy s_stage_elenchi_del on public.s_stage_elenchi for delete to authenticated
  using (public.is_gestione_incarichi());

revoke all on table public.s_stage_elenchi from anon;

alter table public.incarichi
  add column if not exists stage_elenco_id bigint references public.s_stage_elenchi(id) on delete set null;
create index if not exists incarichi_stage_elenco_idx on public.incarichi (stage_elenco_id);

-- ------------------------------------------------------------
-- s_stage_conferma(p_elenco, p_righe)
--   p_elenco: anno_scolastico, classe, sede, dal, al, ore_giorno, ore_totali,
--             richiedente_nome, richiedente_email, data_richiesta, intestazione,
--             file_nome, file_drive_id, file_drive_url, oggetto
--   p_righe:  [{ allievo, impresa, impresa_id, indirizzo, cantiere, comune,
--                tecnico_email, referente, cell_referente, note }]
-- Restituisce { elenco_id, creati: [{id, allievo}], saltati: [{allievo, motivo}] }.
-- Un allievo gia' presente nello stesso elenco NON si ricrea: si salta e lo dice.
-- ------------------------------------------------------------
create or replace function public.s_stage_conferma(p_elenco jsonb, p_righe jsonb)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_mail     text := coalesce(auth.jwt() ->> 'email', 'sistema');
  v_el       bigint;
  v_id       bigint;
  v_r        jsonb;
  v_allievo  text;
  v_tec      record;
  v_creati   jsonb := '[]'::jsonb;
  v_saltati  jsonb := '[]'::jsonb;
  v_oggetto  text;
  v_rich     text;
begin
  if not public.is_gestione_incarichi() then
    raise exception 'Riservato alla segreteria';
  end if;
  if jsonb_typeof(p_righe) is distinct from 'array' then
    raise exception 'Le righe devono essere un elenco';
  end if;
  if jsonb_array_length(p_righe) > 80 then
    raise exception 'Troppe righe in un colpo solo (%): massimo 80', jsonb_array_length(p_righe);
  end if;

  insert into public.s_stage_elenchi as e (
    anno_scolastico, classe, sede, dal, al, ore_giorno, ore_totali,
    richiedente_nome, richiedente_email, data_richiesta, intestazione,
    file_nome, file_drive_id, file_drive_url, creato_da, aggiornato_da)
  values (
    p_elenco ->> 'anno_scolastico',
    (p_elenco ->> 'classe')::smallint,
    p_elenco ->> 'sede',
    nullif(p_elenco ->> 'dal', '')::date,
    nullif(p_elenco ->> 'al', '')::date,
    nullif(p_elenco ->> 'ore_giorno', '')::numeric,
    nullif(p_elenco ->> 'ore_totali', '')::numeric,
    nullif(p_elenco ->> 'richiedente_nome', ''),
    nullif(p_elenco ->> 'richiedente_email', ''),
    coalesce(nullif(p_elenco ->> 'data_richiesta', '')::date, current_date),
    nullif(p_elenco ->> 'intestazione', ''),
    nullif(p_elenco ->> 'file_nome', ''),
    nullif(p_elenco ->> 'file_drive_id', ''),
    nullif(p_elenco ->> 'file_drive_url', ''),
    v_mail, v_mail)
  on conflict (anno_scolastico, classe, sede) do update set
    dal               = coalesce(excluded.dal, e.dal),
    al                = coalesce(excluded.al, e.al),
    ore_giorno        = coalesce(excluded.ore_giorno, e.ore_giorno),
    ore_totali        = coalesce(excluded.ore_totali, e.ore_totali),
    richiedente_nome  = coalesce(excluded.richiedente_nome, e.richiedente_nome),
    richiedente_email = coalesce(excluded.richiedente_email, e.richiedente_email),
    -- il file nuovo (versione aggiornata) prende il posto del vecchio nel
    -- riferimento; il vecchio resta su Drive, dov'era
    file_nome         = coalesce(excluded.file_nome, e.file_nome),
    file_drive_id     = coalesce(excluded.file_drive_id, e.file_drive_id),
    file_drive_url    = coalesce(excluded.file_drive_url, e.file_drive_url),
    aggiornato_il     = now(),
    aggiornato_da     = v_mail
  returning e.id into v_el;

  v_oggetto := coalesce(nullif(p_elenco ->> 'oggetto', ''), 'Visita allo stagista');
  v_rich := coalesce(nullif(p_elenco ->> 'richiedente_nome', ''), 'Didattica ' || (p_elenco ->> 'sede'));

  -- il contatore: nessun altro inserisce incarichi finche' questa transazione non chiude
  lock table public.incarichi in share row exclusive mode;
  select greatest(coalesce((select max(id) from public.incarichi), 0),
                  coalesce((select max(id) from public.s_servizi_storico), 0))
    into v_id;

  for v_r in select * from jsonb_array_elements(p_righe) loop
    v_allievo := btrim(coalesce(v_r ->> 'allievo', ''));

    if v_allievo = '' then
      v_saltati := v_saltati || jsonb_build_object('allievo', '(senza nome)', 'motivo', 'manca il nominativo');
      continue;
    end if;

    if exists (select 1 from public.incarichi i
               where i.stage_elenco_id = v_el
                 and lower(btrim(i.testo_richiesta)) = lower(v_allievo)) then
      v_saltati := v_saltati || jsonb_build_object('allievo', v_allievo, 'motivo', 'gia'' caricato in questo elenco');
      continue;
    end if;

    select t.email,
           concat_ws(' ', t.tecnico_cognome, nullif(t.titolo, ''), t.tecnico_nome) as nome
      into v_tec
      from public.tecnici t
     where lower(t.email) = lower(btrim(coalesce(v_r ->> 'tecnico_email', '')))
       and t.attivo
     limit 1;
    if not found then
      v_saltati := v_saltati || jsonb_build_object('allievo', v_allievo, 'motivo', 'tecnico mancante o non in servizio');
      continue;
    end if;

    v_id := v_id + 1;
    insert into public.incarichi (
      id, data_richiesta, richiedente, mezzo, testo_richiesta,
      tipologia_richiesta, tipo_richiesta, approvato,
      tecnico_nome, tecnico_email,
      impresa, impresa_id, indirizzo, cantiere, comune,
      oggetto, referente, cell_referente, visite_previste,
      stato, note_comunicazione, stage_elenco_id)
    values (
      v_id,
      coalesce(nullif(p_elenco ->> 'data_richiesta', '')::date, current_date),
      v_rich, 'E-Mail', v_allievo,
      -- il gestionale riconosce lo stage da tipo_richiesta (colore, bottone
      -- Relazione, stagista nella visita): va scritto, non basta la tipologia
      'Richiesta Visita STAGE', 'Sopralluogo in Azienda AUDIT ASL/STAGE', true,
      v_tec.nome, v_tec.email,
      nullif(btrim(coalesce(v_r ->> 'impresa', '')), ''),
      nullif(btrim(coalesce(v_r ->> 'impresa_id', '')), ''),
      nullif(btrim(coalesce(v_r ->> 'indirizzo', '')), ''),
      nullif(btrim(coalesce(v_r ->> 'cantiere', '')), ''),
      nullif(upper(btrim(coalesce(v_r ->> 'comune', ''))), ''),
      v_oggetto,
      nullif(btrim(coalesce(v_r ->> 'referente', '')), ''),
      nullif(btrim(coalesce(v_r ->> 'cell_referente', '')), ''),
      1, 'aperto',
      nullif(v_r ->> 'note', ''),
      v_el);

    v_creati := v_creati || jsonb_build_object('id', v_id, 'allievo', v_allievo);
  end loop;

  return jsonb_build_object('elenco_id', v_el, 'creati', v_creati, 'saltati', v_saltati);
end;
$$;

-- la chiave anon sta in un repository pubblico: revoca da public E da anon
revoke execute on function public.s_stage_conferma(jsonb, jsonb) from public, anon;
grant execute on function public.s_stage_conferma(jsonb, jsonb) to authenticated, service_role;
