-- ============================================================================
--  SECONDO CANALE DEL PORTALE SERVIZI  (04/09/2026)  — APPLICATA
--  ---------------------------------------------------------------------------
--  Nasce dall'incidente di agosto 2026: il deployment Apps Script era morto
--  dal ~27/07 e il portale continuava a rispondere «Inviata» perche' inviava
--  in no-cors e non leggeva la risposta. Cinque settimane di moduli persi
--  senza che ne' l'impresa ne' l'ufficio potessero accorgersene.
--
--  Come funziona il doppio riscontro:
--    1. il portale, PRIMA di inviare al foglio, manda una copia della
--       richiesta alla edge function ricezione-portale -> riga qui, con
--       sul_foglio = null («partita, non ancora confermata»);
--    2. il backend Apps Script, a riga scritta sul foglio, CONFERMA quella
--       stessa copia -> sul_foglio = true.
--  Una riga che resta a null per piu' di un quarto d'ora e' una richiesta
--  partita dal portale e mai arrivata al foglio: e' esattamente la perdita
--  che in agosto non si poteva vedere. Il cruscotto della segreteria le
--  conta in tempo reale, senza bisogno di nessun lavoro batch.
--
--  Lo specchio NON e' la fonte: la fonte resta il foglio (e da li' le
--  tabelle di pratica). Serve ad accorgersi, non a lavorare.
-- ============================================================================

create table if not exists s_portale_ricezioni (
  id               bigint generated by default as identity primary key,
  submission_id    text        not null unique,
  tipo             text,
  ricevuto_at      timestamptz not null default now(),
  timestamp_modulo timestamptz,
  ragione_sociale  text,
  email            text,
  payload          jsonb       not null,
  origine          text        not null default 'portale',
  -- riscontro dal backend: null = partita ma non ancora confermata
  sul_foglio       boolean,
  progressivo      integer,
  controllato_il   timestamptz,
  nota             text
);

comment on table s_portale_ricezioni is
  'Specchio degli invii del portale servizi (secondo canale, 04/09/2026). Non e la fonte: serve a riconciliare col foglio Google e ad accorgersi delle richieste perse.';
comment on column s_portale_ricezioni.sul_foglio is
  'null = partita dal portale ma non ancora confermata dal backend (oltre 15 minuti -> da guardare); true = confermata, la riga e sul foglio.';

create index if not exists idx_portale_ric_ricevuto on s_portale_ricezioni (ricevuto_at desc);
create index if not exists idx_portale_ric_daguardare on s_portale_ricezioni (sul_foglio) where sul_foglio is not true;

alter table s_portale_ricezioni enable row level security;

-- La scrive solo la edge function (service role, che salta le policy).
-- Dall'app la legge la segreteria; il Direttore qui non ha nulla da fare.
drop policy if exists sgr_portale_ric_all on s_portale_ricezioni;
create policy sgr_portale_ric_all on s_portale_ricezioni
  for all using (is_segreteria()) with check (is_segreteria());

-- ── chiavi di configurazione ───────────────────────────────────────────────
insert into s_config (chiave, valore, descrizione) values
  ('portale_battito_al', '',
   'Ultimo battito del canale portale servizi, scritto dal backend Apps Script tramite ricezione-portale. Vuoto = mai ricevuto.'),
  ('portale_battito_ore', '36',
   'Oltre quante ore senza battito il cruscotto della segreteria accende l allarme sul canale del portale.'),
  ('portale_battito_token', 'DA-GENERARE',
   'Token con cui il backend Apps Script dichiara il proprio battito a ricezione-portale. Lo stesso valore va nelle Proprieta dello script Apps Script, chiave SUPABASE_BATTITO_TOKEN. Serve perche un battito falsificabile nasconderebbe un guasto.')
on conflict (chiave) do nothing;
