-- ============================================================
-- INCARICHI MENSILI, PRESTAZIONI, FATTURE E MANDATI DEI TECNICI
-- 04/09/2026 — sostituisce le tabelle Access «Comunicazione Visite
-- in cantiere» e «T_ComunicVisiteFatt» (e il campo Ks_Fatt sparso su
-- visite, richieste e lettere di incarico).
--
-- Il disegno, deciso con l'utente:
--   s_incarichi_mensili  la PRATICA MENSILE del tecnico (lettera di
--                        incarico a inizio mese, riepilogo a fine mese);
--                        l'id prosegue la serie Access (max 928).
--   s_prestazioni        il LIBRO MASTRO: una riga per unità pagabile,
--                        con la tariffa congelata e il riferimento
--                        all'origine (visita, incarico, docenza,
--                        asseverazione). È l'unico posto dove vive
--                        «quale fattura ha pagato questa cosa».
--   s_fatture_tecnici    le fatture ricevute (id Access conservato).
--   s_mandati_pagamento  il mandato all'Amministrazione (interno:
--                        numero di pratica, niente protocollo).
--   s_tariffe            tariffe con validità dal/al (100 € prima
--                        visita, 80 € successiva sospesa, 320 €/gg
--                        asseverazione, 50 €/h docenza…).
--   s_tecnici_fiscale    IVA e cassa per tecnico con validità: chi è
--                        forfettario oggi può non esserlo domani.
-- ============================================================

-- ── 1. TARIFFE ──────────────────────────────────────────────
create table if not exists public.s_tariffe (
  id           bigint generated by default as identity primary key,
  codice       text not null,           -- visita_prima | visita_successiva | visita_stage | visita_progetto | docenza_ora | consulenza_ora | conferenza_ora | asseverazione_giorno | coordinamento_ora | altro
  descrizione  text,
  importo      numeric(10,2) not null,
  unita        text not null default 'visita',   -- visita | ora | giorno | forfait
  valido_dal   date not null,
  valido_al    date,
  tecnico_id   text references public.tecnici(tecnico_id),  -- null = vale per tutti
  note         text,
  created_at   timestamptz not null default now(),
  creato_da    text
);
create index if not exists ix_s_tariffe_codice on public.s_tariffe(codice, valido_dal);

-- la tariffa buona per un codice a una data: prima quella del tecnico, poi la generale
create or replace function public.s_tariffa(p_codice text, p_data date, p_tecnico text default null)
returns numeric language sql stable security definer set search_path = public as $$
  select importo from public.s_tariffe
  where codice = p_codice
    and valido_dal <= coalesce(p_data, current_date)
    and (valido_al is null or valido_al >= coalesce(p_data, current_date))
    and (tecnico_id is null or tecnico_id = p_tecnico)
  order by (tecnico_id is not null) desc, valido_dal desc
  limit 1;
$$;

-- ── 2. REGIME FISCALE DEI TECNICI ───────────────────────────
create table if not exists public.s_tecnici_fiscale (
  id          bigint generated by default as identity primary key,
  tecnico_id  text not null references public.tecnici(tecnico_id),
  iva_pct     numeric(5,2) not null default 22,
  cassa_pct   numeric(5,2) not null default 4,
  regime      text,                  -- ordinario | forfettario | …
  valido_dal  date,
  valido_al   date,
  note        text,
  created_at  timestamptz not null default now(),
  creato_da   text
);
create index if not exists ix_s_tecnici_fiscale_tec on public.s_tecnici_fiscale(tecnico_id, valido_dal);

create or replace function public.s_regime_tecnico(p_tecnico text, p_data date default current_date)
returns table (iva_pct numeric, cassa_pct numeric, regime text)
language sql stable security definer set search_path = public as $$
  select f.iva_pct, f.cassa_pct, f.regime from public.s_tecnici_fiscale f
  where f.tecnico_id = p_tecnico
    and (f.valido_dal is null or f.valido_dal <= coalesce(p_data, current_date))
    and (f.valido_al is null or f.valido_al >= coalesce(p_data, current_date))
  order by f.valido_dal desc nulls last
  limit 1;
$$;

-- ── 3. MANDATI DI PAGAMENTO (interni: niente protocollo) ────
create table if not exists public.s_mandati_pagamento (
  id             bigint generated by default as identity primary key,
  data           date not null default current_date,
  totale         numeric(12,2),
  note           text,
  drive_file_id  text,
  drive_url      text,
  mail_at        timestamptz,
  created_at     timestamptz not null default now(),
  creato_da      text
);

-- ── 4. PRATICHE MENSILI (ex «Comunicazione Visite in cantiere») ──
create table if not exists public.s_incarichi_mensili (
  id                    bigint generated by default as identity primary key,
  tecnico_id            text references public.tecnici(tecnico_id),
  tecnico_nome          text,
  tecnico_email         text,
  anno                  int not null,
  mese                  int not null check (mese between 1 and 12),
  data_lettera          date,
  cantieri_assegnati    int default 0,
  seconde_visite        int default 0,
  altro                 int default 0,
  area_zona             int,
  comuni                jsonb,
  note                  text,
  cantieri_visitati     int,          -- storico Access; per le pratiche nuove si conta dalle prestazioni
  hyperlink_com         text,
  hyperlink_qua         text,
  stato                 text not null default 'aperto',   -- aperto | chiuso | fatturato | pagato | annullato
  lettera_protocollo_id bigint references public.s_protocollo(id),
  lettera_drive_id      text,
  lettera_drive_url     text,
  lettera_mail_at       timestamptz,
  riepilogo_protocollo_id bigint references public.s_protocollo(id),
  riepilogo_drive_id    text,
  riepilogo_drive_url   text,
  riepilogo_mail_at     timestamptz,
  totale_netto          numeric(12,2),
  totale_lordo          numeric(12,2),
  chiuso_il             timestamptz,
  chiuso_da             text,
  importato_da_access   boolean not null default false,
  created_at            timestamptz not null default now(),
  creato_da             text,
  updated_at            timestamptz,
  aggiornato_da         text
);
create index if not exists ix_s_inc_mensili_tec on public.s_incarichi_mensili(tecnico_id, anno, mese);

-- ── 5. FATTURE RICEVUTE (ex T_ComunicVisiteFatt) ────────────
create table if not exists public.s_fatture_tecnici (
  id                   bigint generated by default as identity primary key,
  tecnico_id           text references public.tecnici(tecnico_id),
  tecnico_nome         text,
  incarico_mensile_id  bigint references public.s_incarichi_mensili(id),
  numero               text,
  data_fattura         date,
  data_ricevimento     date,
  importo              numeric(12,2),     -- totale fattura (oneri e IVA inclusi)
  imponibile           numeric(12,2),
  cantieri_fatturati   int,
  note                 text,
  stato                text not null default 'attesa',  -- attesa | ricevuta | verificata | approvata | standby | mandato | pagata | annullata
  verificata_da        text,
  verificata_il        date,
  approvata_da         text,
  approvata_il         date,
  standby_motivo       text,
  standby_il           timestamptz,
  standby_da           text,
  mandato_id           bigint references public.s_mandati_pagamento(id),
  mandato_data         date,             -- storico Access «Mandato di Pagamento»
  protocollo_in_id     bigint references public.s_protocollo(id),
  drive_file_id        text,
  drive_url            text,
  importato_da_access  boolean not null default false,
  created_at           timestamptz not null default now(),
  creato_da            text,
  updated_at           timestamptz,
  aggiornato_da        text
);
create index if not exists ix_s_fatture_tec on public.s_fatture_tecnici(tecnico_id, data_ricevimento);
create index if not exists ix_s_fatture_inc on public.s_fatture_tecnici(incarico_mensile_id);

-- ── 6. PRESTAZIONI: il libro mastro ─────────────────────────
create table if not exists public.s_prestazioni (
  id                   bigint generated by default as identity primary key,
  tecnico_id           text references public.tecnici(tecnico_id),
  tecnico_nome         text,
  data                 date not null,
  anno                 int not null,     -- competenza (mese del riepilogo)
  mese                 int not null,
  tipo                 text not null,    -- visita_prima | visita_successiva | visita_stage | visita_progetto | docenza | consulenza | conferenza | asseverazione | coordinamento | altro
  descrizione          text,
  quantita             numeric(8,2) not null default 1,
  unita                text default 'visita',
  tariffa_codice       text,
  tariffa_unitaria     numeric(10,2),
  importo              numeric(12,2),    -- netto (senza cassa e IVA)
  visita_id            text references public.visite(visita_id),
  incarico_id          bigint references public.incarichi(id),
  corso_incarico_id    bigint references public.s_corsi_incarichi(id),
  a_pratica_id         uuid references public.a_pratica(id),
  progetto_id          bigint references public.s_progetti_formativi(id),
  incarico_mensile_id  bigint references public.s_incarichi_mensili(id),
  fattura_id           bigint references public.s_fatture_tecnici(id),
  origine              text not null default 'chiusura',   -- access | chiusura | manuale
  note                 text,
  created_at           timestamptz not null default now(),
  creato_da            text
);
create unique index if not exists ux_s_prestazioni_visita on public.s_prestazioni(visita_id) where visita_id is not null;
create unique index if not exists ux_s_prestazioni_corso on public.s_prestazioni(corso_incarico_id) where corso_incarico_id is not null;
create index if not exists ix_s_prestazioni_tec on public.s_prestazioni(tecnico_id, anno, mese);
create index if not exists ix_s_prestazioni_fatt on public.s_prestazioni(fattura_id);
create index if not exists ix_s_prestazioni_incm on public.s_prestazioni(incarico_mensile_id);
create index if not exists ix_s_prestazioni_prog on public.s_prestazioni(progetto_id);

-- ── 7. colonne nuove sulle tabelle esistenti ────────────────
alter table public.visite
  add column if not exists progetto_id bigint references public.s_progetti_formativi(id),
  add column if not exists senza_rapporto boolean not null default false,
  add column if not exists relazione text;
comment on column public.visite.senza_rapporto is 'Visita stage fuori provincia senza rapporto di sopralluogo: al posto del verbale c''è una relazione (campo relazione). Si conta e si paga come le altre.';

alter table public.a_pratica
  add column if not exists fattura_impresa_num text,
  add column if not exists fattura_impresa_imponibile numeric(10,2);
comment on column public.a_pratica.fattura_impresa_num is 'Numero della fattura emessa dall''ENTE all''impresa asseverata (t_ASS.NFatt): serve a chiedere a Patrizia se è stata fatturata. NON è la fattura del tecnico.';

insert into public.s_tipo_doc (id_doc, descrizione) values
  (61, 'Fattura tecnico'),
  (62, 'Comunicazione visite mensili al tecnico'),
  (63, 'Riepilogo attività da fatturare')
on conflict (id_doc) do nothing;

insert into public.s_config (chiave, valore, descrizione) values
  ('coordinatore_email', 'nicola.demarco@did.formedilpadova.it', 'Coordinatore Area Sicurezza: dà l''ok alle fatture dei tecnici'),
  ('coordinatore_nome', 'Arch. Nicola De Marco', 'Nome del coordinatore per visti e mail'),
  ('amministrazione_email', 'amministrazione@formedilpadova.it', 'Amministrazione (Patrizia): riceve riepiloghi in copia e mandati'),
  ('incarico_visite_testo', 'ATTENZIONE
📌 Assegnazione cantieri:
- Cantieri stradali dell''impresa VERONESE → seguiti dall''Arch. Nicola, indipendentemente dalla zona.
- Cantiere dell''impresa The Builder in Z.I. Padova (Padova) → seguito dall''Arch. Nicola.
📩 Comunicazioni con il CPT e per le visite in cantiere
Utilizzare esclusivamente il proprio account: nome.cognome@did.formedilpadova.it
---
Modalità Visite e Consulenze
1) Durata degli incarichi: le visite assegnate dalla Segreteria sono valide per un mese. Dopo la scadenza, l''incarico non sarà più valido.
2) Comunicazione degli appuntamenti: se si riceve un incarico per consulenza, è necessario comunicare la data dell''appuntamento fissato.
3) Tempistiche: se non è possibile svolgere l''incarico entro 4-5 giorni, avvisare tempestivamente la Segreteria.
4) Fatturazione: a fine mese riceverete un riepilogo con i conteggi per l''emissione della fattura.
5) Priorità cantieri: dare precedenza ai cantieri delle imprese iscritte alla C.E.I.V.
6) Evitare conflitti di interesse: non effettuare visite o consulenze per imprese con cui si hanno collaborazioni in libera professione. In tal caso, avvisare la Segreteria che provvederà ad assegnare l''incarico a un altro tecnico.
7) Promemoria pratiche aperte: la comunicazione inviata include la lista dei cantieri con NC per facilitare la chiusura delle pratiche aperte.
8) Affiancamento con RLST (Sauro Cazzoli): per concordare le visite in affiancamento, contattarlo al 349 2979481.
---
Per qualsiasi dubbio o chiarimento, sono a disposizione. Grazie a tutti per la collaborazione!', 'Testo standard in coda alla lettera mensile di incarico visite (ex campo NOTE di Access)'),
  ('rlst_minimo_pct', '20', 'Percentuale minima di visite con RLST nel mese (avviso sul riepilogo)')
on conflict (chiave) do nothing;

-- ── 8. tariffe e regimi di partenza ─────────────────────────
-- (serie storica in 2_AREE/Amministrazione/contratti/TARIFFE dei tecnici - serie storica 2007-2026.md)
insert into public.s_tariffe (codice, descrizione, importo, unita, valido_dal, valido_al, note, creato_da)
select * from (values
  ('visita_prima',       'Prima visita in cantiere',                       100.00, 'visita', date '2021-06-01', null::date, 'contratti dal 01/06/2021', 'migrazione 04/09/2026'),
  ('visita_successiva',  'Accesso successivo allo stesso cantiere',         80.00, 'visita', date '2021-06-01', date '2025-03-31', 'contratto modello 2021; sospesa dal 2025: tutte le visite a 100 € per decisione di Balladore (data di inizio da confermare)', 'migrazione 04/09/2026'),
  ('visita_successiva',  'Accesso successivo allo stesso cantiere',        100.00, 'visita', date '2025-04-01', null::date, 'tutte le visite a 100 € (decisione Balladore); quando torna la seconda visita a 80 € si chiude questa riga e se ne apre una nuova', 'migrazione 04/09/2026'),
  ('visita_stage',       'Visita stage (con o senza rapporto)',            100.00, 'visita', date '2021-06-01', null::date, 'a tutti gli effetti una visita ordinaria', 'migrazione 04/09/2026'),
  ('visita_progetto',    'Visita di progetto (audit in cantiere)',         100.00, 'visita', date '2021-06-01', null::date, null, 'migrazione 04/09/2026'),
  ('docenza_ora',        'Docenza (ora)',                                   50.00, 'ora',    date '2018-01-01', null::date, 'incarichi docenza 2018-2026; corsi con tariffa diversa la portano sull''incarico', 'migrazione 04/09/2026'),
  ('consulenza_ora',     'Consulenza / informazione (ora)',                 50.00, 'ora',    date '2020-01-01', null::date, 'modello contratto 2020, ancora nel 2026', 'migrazione 04/09/2026'),
  ('conferenza_ora',     'Conferenza di cantiere (ora)',                    50.00, 'ora',    date '2020-01-01', null::date, null, 'migrazione 04/09/2026'),
  ('asseverazione_giorno','Asseverazione: giornata uomo (asseveratori interni)', 320.00, 'giorno', date '2019-01-01', null::date, 'confermato dall''utente 04/09/2026; gli esterni (Parasiliti) su contrattazione col Direttore', 'migrazione 04/09/2026'),
  ('coordinamento_ora',  'Attività di coordinamento (ora)',                 50.00, 'ora',    date '2026-01-01', null::date, 'contratto De Marco 2026', 'migrazione 04/09/2026')
) as v(codice, descrizione, importo, unita, valido_dal, valido_al, note, creato_da)
where not exists (select 1 from public.s_tariffe);

-- IVA e cassa come stavano in Access (Dipendenti.IVA / CassaPrev), letti il 04/09/2026
insert into public.s_tecnici_fiscale (tecnico_id, iva_pct, cassa_pct, regime, valido_dal, note, creato_da)
select t.tecnico_id, v.iva, v.cassa, case when v.iva = 0 then 'forfettario' else 'ordinario' end, null, 'da anagrafica Access (Dipendenti.IVA/CassaPrev) al 04/09/2026', 'migrazione 04/09/2026'
from (values
  ('paolo.balladore@did.formedilpadova.it', 22, 4),
  ('nicola.demarco@did.formedilpadova.it',   0, 4),
  ('franco.caon@did.formedilpadova.it',     22, 4),
  ('marco.camuffo@did.formedilpadova.it',    0, 4),
  ('tommaso.visentini@did.formedilpadova.it',22, 4),
  ('mirco.canova@did.formedilpadova.it',     0, 5),
  ('alberto.lorenzin@did.formedilpadova.it', 22, 4)
) as v(email, iva, cassa)
join public.tecnici t on lower(t.email) = v.email
where not exists (select 1 from public.s_tecnici_fiscale);

-- ── 9. ruolo coordinatore ───────────────────────────────────
create or replace function public.is_coordinatore()
returns boolean language sql stable security definer set search_path = public as $$
  select exists (
    select 1 from public.s_config c
    where c.chiave = 'coordinatore_email'
      and lower(c.valore) = lower(coalesce(auth.jwt() ->> 'email', ''))
  );
$$;

-- il tecnico che sta guardando (per le policy «vedo le mie righe»)
create or replace function public.s_mio_tecnico_id()
returns text language sql stable security definer set search_path = public as $$
  select t.tecnico_id from public.tecnici t
  where lower(t.email) = lower(coalesce(auth.jwt() ->> 'email', ''))
  order by t.attivo desc limit 1;
$$;

-- ── 10. la pratica mensile tiene allineato il target del gestionale ──
-- (target_visite_mensili è la card «obiettivo del mese» che il tecnico
-- vede già nel gestionale: non si duplica, si alimenta da qui)
create or replace function public.s_inc_mensile_sync_target()
returns trigger language plpgsql security definer set search_path = public as $$
begin
  if new.tecnico_id is not null and new.cantieri_assegnati is not null and new.stato <> 'annullato' then
    insert into public.target_visite_mensili (tecnico_id, anno, mese, max_visite, updated_at)
    values (new.tecnico_id, new.anno, new.mese, new.cantieri_assegnati, now())
    on conflict (tecnico_id, anno, mese) do update set max_visite = excluded.max_visite, updated_at = now();
  end if;
  return new;
end $$;
drop trigger if exists trg_s_inc_mensile_sync_target on public.s_incarichi_mensili;
create trigger trg_s_inc_mensile_sync_target
  after insert or update of cantieri_assegnati, stato on public.s_incarichi_mensili
  for each row when (new.importato_da_access = false) execute function public.s_inc_mensile_sync_target();

-- ── 11. LE PRESTAZIONI DEL MESE, calcolate dalle fonti ──────
-- Restituisce le righe candidate al riepilogo di un tecnico per un
-- mese: visite (dal gestionale), docenze (s_corsi_incarichi), servizi
-- con corrispettivo (incarichi), asseverazioni (a_pratica). Ogni riga
-- dice se è GIÀ registrata in s_prestazioni (e con quale fattura):
-- finché il mese è aperto è un'anteprima, alla chiusura si congela.
create or replace function public.s_prestazioni_calcola(p_tecnico text, p_anno int, p_mese int)
returns jsonb language plpgsql stable security definer set search_path = public as $$
declare
  v_dal date := make_date(p_anno, p_mese, 1);
  v_al  date := (make_date(p_anno, p_mese, 1) + interval '1 month - 1 day')::date;
  v_email text;
  v_cognome text;
  v_out jsonb := '[]'::jsonb;
begin
  select lower(email), tecnico_cognome into v_email, v_cognome from public.tecnici where tecnico_id = p_tecnico;

  /* a) visite */
  v_out := v_out || coalesce((
    select jsonb_agg(jsonb_build_object(
      'sorgente', 'visita', 'visita_id', v.visita_id, 'nr_verbale', v.nr_verbale,
      'data', v.data_visita, 'stato_visita', v.stato,
      'tipo', t.tipo, 'tariffa_codice', t.tipo,
      'tariffa_unitaria', public.s_tariffa(t.tipo, v.data_visita, p_tecnico),
      'quantita', 1, 'unita', 'visita',
      'importo', public.s_tariffa(t.tipo, v.data_visita, p_tecnico),
      'descrizione', concat_ws(' — ', coalesce(i.impresa_nome, v.impresa_rl_nome), c.comune_nome,
                       case when v.senza_rapporto then 'stage senza rapporto' else null end,
                       case when v.rlst_sn then 'con RLST' else null end),
      'impresa', coalesce(i.impresa_nome, v.impresa_rl_nome), 'comune', c.comune_nome,
      'accesso_n', v.acc_cant, 'tipo_accesso', v.tipo_accesso, 'rlst', v.rlst_sn, 'stage', coalesce(v.stage_vis, false) or v.senza_rapporto,
      'progetto_id', v.progetto_id, 'cantiere_id', v.cantiere_id,
      'prestazione_id', p.id, 'fattura_id', p.fattura_id, 'incarico_mensile_id', p.incarico_mensile_id
    ) order by v.data_visita, v.nr_verbale)
    from public.visite v
    left join public.imprese i on i.impresa_id = v.impresa_id
    left join public.cantieri c on c.cantiere_id = v.cantiere_id
    left join public.s_prestazioni p on p.visita_id = v.visita_id
    cross join lateral (select case
        when v.senza_rapporto or coalesce(v.stage_vis, false) or v.tipo_accesso = 9 then 'visita_stage'
        when v.progetto_id is not null and v.progetto_id not in (14) then 'visita_progetto'
        when coalesce(nullif(regexp_replace(coalesce(v.acc_cant, ''), '\D', '', 'g'), ''), '1')::int > 1 then 'visita_successiva'
        else 'visita_prima' end as tipo) t
    where v.tecnico_id = p_tecnico and v.elimina is distinct from 1
      and v.data_visita between v_dal and v_al
  ), '[]'::jsonb);

  /* a2) visite stage fuori provincia, senza verbale (s_visite_stage) */
  v_out := v_out || coalesce((
    select jsonb_agg(jsonb_build_object(
      'sorgente', 'stage', 'visita_stage_id', s.id,
      'data', s.data, 'tipo', 'visita_stage', 'tariffa_codice', 'visita_stage',
      'tariffa_unitaria', public.s_tariffa('visita_stage', s.data, p_tecnico),
      'quantita', 1, 'unita', 'visita',
      'importo', public.s_tariffa('visita_stage', s.data, p_tecnico),
      'descrizione', concat_ws(' — ', s.azienda, concat_ws(' ', s.comune, case when s.provincia is not null then '(' || s.provincia || ')' end), 'stage fuori provincia senza verbale', case when s.stagista is not null then 'stagista ' || s.stagista end),
      'impresa', s.azienda, 'comune', s.comune, 'stage', true, 'rlst', false, 'tipo_accesso', 9, 'progetto_id', 15,
      'prestazione_id', p.id, 'fattura_id', p.fattura_id, 'incarico_mensile_id', p.incarico_mensile_id
    ) order by s.data)
    from public.s_visite_stage s
    left join public.s_prestazioni p on p.visita_stage_id = s.id
    where s.tecnico_id = p_tecnico and s.stato = 'registrata' and s.data between v_dal and v_al
  ), '[]'::jsonb);

  /* b) docenze (lettere di incarico dei corsi) */
  v_out := v_out || coalesce((
    select jsonb_agg(jsonb_build_object(
      'sorgente', 'docenza', 'corso_incarico_id', k.id, 'corso_id', k.corso_id,
      'data', coalesce(k.data_incarico, c.data_inizio),
      'tipo', 'docenza', 'tariffa_codice', 'docenza_ora',
      'tariffa_unitaria', coalesce(k.tariffa_oraria, public.s_tariffa('docenza_ora', coalesce(k.data_incarico, c.data_inizio), p_tecnico)),
      'quantita', coalesce(k.ore, 0), 'unita', 'ora',
      'importo', coalesce(k.corrispettivo, coalesce(k.ore, 0) * coalesce(k.tariffa_oraria, public.s_tariffa('docenza_ora', coalesce(k.data_incarico, c.data_inizio), p_tecnico))),
      'descrizione', concat_ws(' — ', 'Corso n° ' || k.corso_id, c.titolo),
      'progetto_id', c.progetto_id, 'prot_out_id', k.protocollo_out_id,
      'prestazione_id', p.id, 'fattura_id', p.fattura_id, 'incarico_mensile_id', p.incarico_mensile_id
    ) order by k.data_incarico)
    from public.s_corsi_incarichi k
    join public.s_corsi c on c.id = k.corso_id
    left join public.s_prestazioni p on p.corso_incarico_id = k.id
    where coalesce(k.data_incarico, c.data_inizio) between v_dal and v_al
      and (
        exists (select 1 from public.persone pe join public.tecnici t on lower(t.email) = lower(pe.email) where pe.persona_id = k.persona_id and t.tecnico_id = p_tecnico)
        or (v_cognome is not null and k.nominativo ilike '%' || v_cognome || '%')
      )
  ), '[]'::jsonb);

  /* c) servizi con corrispettivo (incarichi del gestionale) */
  v_out := v_out || coalesce((
    select jsonb_agg(jsonb_build_object(
      'sorgente', 'incarico', 'incarico_id', i.id,
      'data', coalesce(i.eseguito_il::date, i.data_risposta, i.data_richiesta),
      'tipo', case when coalesce(i.tipologia_richiesta, i.tipo_richiesta, i.oggetto, '') ilike '%conferenz%' then 'conferenza'
                   when coalesce(i.tipologia_richiesta, i.tipo_richiesta, i.oggetto, '') ilike '%consulen%' then 'consulenza'
                   else 'altro' end,
      'tariffa_codice', null,
      'tariffa_unitaria', i.corrispettivo, 'quantita', coalesce(i.ore, 1), 'unita', 'ora',
      'importo', i.corrispettivo * coalesce(i.ore, 1),
      'descrizione', concat_ws(' — ', 'Incarico n° ' || i.id, coalesce(i.tipologia_richiesta, i.tipo_richiesta), i.impresa, i.comune),
      'avviso', case when i.visita_id is not null or exists (select 1 from public.visite vv where vv.prot_int = i.id::text)
                     then 'ha una visita collegata: se già conteggiata fra le visite, non aggiungere' else null end,
      'prestazione_id', p.id, 'fattura_id', p.fattura_id, 'incarico_mensile_id', p.incarico_mensile_id
    ) order by i.data_richiesta)
    from public.incarichi i
    left join public.s_prestazioni p on p.incarico_id = i.id
    where lower(coalesce(i.tecnico_email, '')) = coalesce(v_email, '')
      and coalesce(i.corrispettivo, 0) > 0
      and coalesce(i.eseguito_il::date, i.data_risposta, i.data_richiesta) between v_dal and v_al
  ), '[]'::jsonb);

  /* d) asseverazioni (verifica conclusa nel mese) */
  v_out := v_out || coalesce((
    select jsonb_agg(jsonb_build_object(
      'sorgente', 'asseverazione', 'a_pratica_id', a.id, 'numero_protocollo', a.numero_protocollo,
      'data', coalesce(a.data_fine_verifica, a.data_inizio_verifica, a.data_incarico),
      'tipo', 'asseverazione', 'tariffa_codice', 'asseverazione_giorno',
      'tariffa_unitaria', coalesce(a.incarico_tariffa_giornaliera, public.s_tariffa('asseverazione_giorno', coalesce(a.data_fine_verifica, a.data_incarico)::date, p_tecnico)),
      'quantita', coalesce(a.incarico_giornate, 1), 'unita', 'giorno',
      'importo', coalesce(a.incarico_compenso, coalesce(a.incarico_giornate, 1) * coalesce(a.incarico_tariffa_giornaliera, public.s_tariffa('asseverazione_giorno', coalesce(a.data_fine_verifica, a.data_incarico)::date, p_tecnico))),
      'descrizione', concat_ws(' — ', 'Asseverazione ' || coalesce(a.numero_protocollo, ''), a.tipo::text, id_imp.impresa_nome),
      'progetto_id', 18,
      'prestazione_id', p.id, 'fattura_id', p.fattura_id, 'incarico_mensile_id', p.incarico_mensile_id
    ) order by a.data_fine_verifica)
    from public.a_pratica a
    left join public.imprese id_imp on id_imp.impresa_id = a.impresa_id::text
    left join public.s_prestazioni p on p.a_pratica_id = a.id
    where (a.tecnico_principale::text = p_tecnico or a.tecnico_verificatore2::text = p_tecnico)
      and coalesce(a.data_fine_verifica, a.data_inizio_verifica, a.data_incarico)::date between v_dal and v_al
  ), '[]'::jsonb);

  return v_out;
end $$;

-- ── 12. decisione del coordinatore sulla fattura ────────────
create or replace function public.s_fattura_decisione(p_id bigint, p_esito text, p_motivo text default null)
returns public.s_fatture_tecnici language plpgsql security definer set search_path = public as $$
declare v public.s_fatture_tecnici; v_chi text := coalesce(auth.jwt() ->> 'email', 'sistema');
begin
  if not (public.is_coordinatore() or public.is_segreteria()) then raise exception 'Non autorizzato'; end if;
  if p_esito = 'approvata' then
    update public.s_fatture_tecnici set stato = 'approvata', approvata_da = v_chi, approvata_il = current_date,
      standby_motivo = null, updated_at = now(), aggiornato_da = v_chi where id = p_id returning * into v;
  elsif p_esito = 'standby' then
    update public.s_fatture_tecnici set stato = 'standby', standby_motivo = p_motivo, standby_il = now(), standby_da = v_chi,
      updated_at = now(), aggiornato_da = v_chi where id = p_id returning * into v;
  else
    raise exception 'Esito non valido: %', p_esito;
  end if;
  return v;
end $$;

-- ── 13. RLS ─────────────────────────────────────────────────
alter table public.s_tariffe enable row level security;
alter table public.s_tecnici_fiscale enable row level security;
alter table public.s_mandati_pagamento enable row level security;
alter table public.s_incarichi_mensili enable row level security;
alter table public.s_fatture_tecnici enable row level security;
alter table public.s_prestazioni enable row level security;

drop policy if exists sgr_tariffe_all on public.s_tariffe;
create policy sgr_tariffe_all on public.s_tariffe for all using (public.is_segreteria()) with check (public.is_segreteria());
drop policy if exists auth_tariffe_sel on public.s_tariffe;
create policy auth_tariffe_sel on public.s_tariffe for select to authenticated using (true);

drop policy if exists sgr_fiscale_all on public.s_tecnici_fiscale;
create policy sgr_fiscale_all on public.s_tecnici_fiscale for all using (public.is_segreteria()) with check (public.is_segreteria());
drop policy if exists tec_fiscale_sel on public.s_tecnici_fiscale;
create policy tec_fiscale_sel on public.s_tecnici_fiscale for select to authenticated using (tecnico_id = public.s_mio_tecnico_id() or public.is_coordinatore());

drop policy if exists sgr_mandati_all on public.s_mandati_pagamento;
create policy sgr_mandati_all on public.s_mandati_pagamento for all using (public.is_segreteria()) with check (public.is_segreteria());
drop policy if exists dir_mandati_sel on public.s_mandati_pagamento;
create policy dir_mandati_sel on public.s_mandati_pagamento for select to authenticated using (public.is_coordinatore() or public.is_direttore());

drop policy if exists sgr_incm_all on public.s_incarichi_mensili;
create policy sgr_incm_all on public.s_incarichi_mensili for all using (public.is_segreteria()) with check (public.is_segreteria());
drop policy if exists tec_incm_sel on public.s_incarichi_mensili;
create policy tec_incm_sel on public.s_incarichi_mensili for select to authenticated using (tecnico_id = public.s_mio_tecnico_id() or public.is_coordinatore() or public.is_direttore());

drop policy if exists sgr_fatt_all on public.s_fatture_tecnici;
create policy sgr_fatt_all on public.s_fatture_tecnici for all using (public.is_segreteria()) with check (public.is_segreteria());
drop policy if exists tec_fatt_sel on public.s_fatture_tecnici;
create policy tec_fatt_sel on public.s_fatture_tecnici for select to authenticated using (tecnico_id = public.s_mio_tecnico_id() or public.is_coordinatore() or public.is_direttore());

drop policy if exists sgr_prest_all on public.s_prestazioni;
create policy sgr_prest_all on public.s_prestazioni for all using (public.is_segreteria()) with check (public.is_segreteria());
drop policy if exists tec_prest_sel on public.s_prestazioni;
create policy tec_prest_sel on public.s_prestazioni for select to authenticated using (tecnico_id = public.s_mio_tecnico_id() or public.is_coordinatore() or public.is_direttore());

grant execute on function public.s_tariffa(text, date, text) to authenticated;
grant execute on function public.s_regime_tecnico(text, date) to authenticated;
grant execute on function public.is_coordinatore() to authenticated;
grant execute on function public.s_mio_tecnico_id() to authenticated;
grant execute on function public.s_prestazioni_calcola(text, int, int) to authenticated;
grant execute on function public.s_fattura_decisione(bigint, text, text) to authenticated;

-- ── 14. VISITE STAGE FUORI PROVINCIA SENZA VERBALE (04/09/2026) ──
-- Il tecnico non compila il rapporto (non e' una visita ordinaria) ma
-- manda una relazione, e la visita si paga come le altre. La tabella
-- visite pretende cantiere, impresa e numero di verbale: questa e' una
-- tabella a se', che entra nel calcolo delle prestazioni (blocco a2).
create table if not exists public.s_visite_stage (
  id bigint generated by default as identity primary key,
  tecnico_id text not null references public.tecnici(tecnico_id),
  data date not null,
  azienda text,
  comune text,
  provincia text,
  stagista text,
  relazione text,
  note text,
  stato text not null default 'registrata' check (stato in ('registrata','annullata')),
  created_at timestamptz default now(),
  creato_da text,
  updated_at timestamptz,
  aggiornato_da text
);
create index if not exists s_visite_stage_tec_data on public.s_visite_stage(tecnico_id, data);
alter table public.s_prestazioni add column if not exists visita_stage_id bigint references public.s_visite_stage(id);
create unique index if not exists s_prestazioni_visita_stage_uq on public.s_prestazioni(visita_stage_id) where visita_stage_id is not null;
alter table public.s_visite_stage enable row level security;
drop policy if exists sgr_vstage_all on public.s_visite_stage;
create policy sgr_vstage_all on public.s_visite_stage for all using (public.is_segreteria()) with check (public.is_segreteria());
drop policy if exists tec_vstage_sel on public.s_visite_stage;
create policy tec_vstage_sel on public.s_visite_stage for select to authenticated
  using (tecnico_id = public.s_mio_tecnico_id() or public.is_coordinatore() or public.is_direttore());
drop policy if exists tec_vstage_ins on public.s_visite_stage;
create policy tec_vstage_ins on public.s_visite_stage for insert to authenticated with check (tecnico_id = public.s_mio_tecnico_id());
drop policy if exists tec_vstage_upd on public.s_visite_stage;
create policy tec_vstage_upd on public.s_visite_stage for update to authenticated
  using (tecnico_id = public.s_mio_tecnico_id() and not exists (select 1 from public.s_prestazioni p where p.visita_stage_id = s_visite_stage.id and p.fattura_id is not null))
  with check (tecnico_id = public.s_mio_tecnico_id());
